// <auto-generated />
using System;
using AppFletesMueve.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppFletesMueve.Api.Migrations
{
    [DbContext(typeof(MueveDbContext))]
    partial class MueveDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppFletesMueve.Api.Models.ChatMessage", b =>
                {
                    b.Property<int>("ChatMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChatMessageId"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReadBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReadTimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SolicitudFleteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ChatMessageId");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("AppFletesMueve.Api.Models.Conductor", b =>
                {
                    b.Property<int>("ConductorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConductorId"));

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<string>("Licencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("ConductorId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Conductores", (string)null);
                });

            modelBuilder.Entity("AppFletesMueve.Api.Models.SolicitudCarga", b =>
                {
                    b.Property<int>("SolicitudCargaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SolicitudCargaId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<double>("PesoKg")
                        .HasColumnType("double precision");

                    b.Property<int>("SolicitudFleteId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoCargaId")
                        .HasColumnType("integer");

                    b.Property<double>("VolumenM3")
                        .HasColumnType("double precision");

                    b.HasKey("SolicitudCargaId");

                    b.HasIndex("SolicitudFleteId");

                    b.HasIndex("TipoCargaId");

                    b.ToTable("SolicitudesCarga", (string)null);
                });

            modelBuilder.Entity("AppFletesMueve.Api.Models.SolicitudFlete", b =>
                {
                    b.Property<int>("SolicitudFleteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SolicitudFleteId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int?>("ConductorId")
                        .HasColumnType("integer");

                    b.Property<string>("DireccionDestino")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DireccionOrigen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DistanciaKm")
                        .HasColumnType("double precision");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("FechaProgramada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("LatitudDestino")
                        .HasColumnType("double precision");

                    b.Property<double>("LatitudOrigen")
                        .HasColumnType("double precision");

                    b.Property<double>("LongitudDestino")
                        .HasColumnType("double precision");

                    b.Property<double>("LongitudOrigen")
                        .HasColumnType("double precision");

                    b.Property<decimal>("Precio")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("TipoServicio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoVehiculo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Utilitario");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("SolicitudFleteId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ConductorId");

                    b.HasIndex("Estado");

                    b.HasIndex("VehiculoId");

                    b.ToTable("SolicitudesFlete", (string)null);
                });

            modelBuilder.Entity("AppFletesMueve.Api.Models.TipoCarga", b =>
                {
                    b.Property<int>("TipoCargaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoCargaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PesoEstimadoKg")
                        .HasColumnType("double precision");

                    b.Property<double>("VolumenEstimadoM3")
                        .HasColumnType("double precision");

                    b.HasKey("TipoCargaId");

                    b.ToTable("TiposCarga", (string)null);
                });

            modelBuilder.Entity("AppFletesMueve.Api.Models.ChatMessage", b =>
                {
                    b.Property<int>("ChatMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChatMessageId"));

                    b.Property<int>("SolicitudFleteId")
                        .HasColumnType("integer");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ReadTimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReadBy")
                        .HasColumnType("text");

                    b.HasKey("ChatMessageId");

                    b.HasIndex("SolicitudFleteId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("AppFletesMueve.Api.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("AppFletesMueve.Api.Models.Vehiculo", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VehiculoId"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<double>("CapacidadKg")
                        .HasColumnType("double precision");

                    b.Property<int>("ConductorId")
                        .HasColumnType("integer");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean");

                    b.Property<string>("Imagen")
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TipoVehiculo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<double>("VolumenM3")
                        .HasColumnType("double precision");

                    b.HasKey("VehiculoId");

                    b.HasIndex("ConductorId");

                    b.HasIndex("Patente")
                        .IsUnique();

                    b.ToTable("Vehiculos", (string)null);
                });

            modelBuilder.Entity("AppFletesMueve.Api.Models.Conductor", b =>
                {
                    b.HasOne("AppFletesMueve.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppFletesMueve.Api.Models.SolicitudCarga", b =>
                {
                    b.HasOne("AppFletesMueve.Api.Models.SolicitudFlete", "SolicitudFlete")
                        .WithMany("Cargas")
                        .HasForeignKey("SolicitudFleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppFletesMueve.Api.Models.TipoCarga", "TipoCarga")
                        .WithMany()
                        .HasForeignKey("TipoCargaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SolicitudFlete");

                    b.Navigation("TipoCarga");
                });

            modelBuilder.Entity("AppFletesMueve.Api.Models.SolicitudFlete", b =>
                {
                    b.HasOne("AppFletesMueve.Api.Models.Usuario", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppFletesMueve.Api.Models.Conductor", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AppFletesMueve.Api.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("Conductor");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("AppFletesMueve.Api.Models.Vehiculo", b =>
                {
                    b.HasOne("AppFletesMueve.Api.Models.Conductor", "Conductor")
                        .WithMany("Vehiculos")
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conductor");
                });

            modelBuilder.Entity("AppFletesMueve.Api.Models.Conductor", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("AppFletesMueve.Api.Models.SolicitudFlete", b =>
                {
                    b.Navigation("Cargas");
                });
#pragma warning restore 612, 618
        }
    }
}
